name: BWEvent
description: A Spigot 1.19 plugin extension for the plugin ScreamingBedwars
version: 1.0.0
main: fr.fewerelk.eventplugin.EventPlugin 
author: FewerElk
website: github.com/FewerElk/EventPlugin
api-version: 1.19
load: POSTWORLD
depend: [BedWars, Vault]
loadbefore: [BedWars, Vault]
commands:
  buycommand:
    description: Buy a command for bedwars games
    aliases: 
    - buycmd
    - bcmd
    usage: /<command> <article>
  modifycmd:
    description: Modify the command to buy
    permission: betheconsole
    aliases: 
    - mcmd
    permission-message: YOu have to be in the console to perform this command ! Contact the admin !
    usage: /<command> [setcmd|setprice|setenabled] <value>